GolmohammadiProject/Controllers/SellFormController.cs
using Golmohammadi.Models.Models.Factor;
using GolMohammadi.Business.SellFormService;
using Microsoft.AspNetCore.Mvc;

namespace GolmohammadiProject.Controllers
{
    public class SellFormController : Controller
    {
        private ISellFormService _sellFormService;

        public SellFormController(ISellFormService sellFormService)
        {
            _sellFormService = sellFormService;
        }

        [HttpGet]
        public async Task<IActionResult> GetSellForms()
        {
            List<SellForm> sellForms = await _sellFormService.GetAllSellForm();
            return View(sellForms);
        }

        [HttpGet]
        public IActionResult CreateSellForm()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateSellForms(SellForm sellForm)
        {
            await _sellFormService.Create(sellForm);
            return RedirectToAction("GetSellForms");
        }

        [HttpGet]
        public async Task<IActionResult> EditSellForm(int id)
        {
            var sellForm = await _sellFormService.GetById(id);
            return View(sellForm);
        }

        [HttpPost]
        public async Task<IActionResult> EditSellForm(SellForm sellForm)
        {
            await _sellFormService.Update(sellForm);
            return RedirectToAction("GetSellForms");
        }

        [HttpGet]
        public async Task<IActionResult> DeleteSellForm(int id)
        {
            var sellForm = await _sellFormService.GetById(id);
            return View(sellForm);
        }

        [HttpPost, ActionName("DeleteSellForm")]
        public async Task<IActionResult> DeleteSellForms(int id)
        {
            await _sellFormService.Delete(id);
            return RedirectToAction("GetSellForms");
        }
    }
}

GolmohammadiProject/Views/SellForm/CreateSellForm.cshtml
@using Golmohammadi.Models.Models.Factor
@model SellForm

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create</h2>
            <hr />
        </div>
        <div class="mb-3 row">
            <label asp-for="ProductName" class="p-0"></label>
            <input asp-for="ProductName" class="form-control" />
            <span asp-validation-for="ProductName" class="text-danger"></span>
        </div>
        <div class="mb-3 row">
            <label asp-for="Unit" class="p-0"></label>
            <input asp-for="Unit" class="form-control" />
            <span asp-validation-for="Unit" class="text-danger"></span>
        </div>
        <div class="mb-3 row">
            <label asp-for="TransportationPrice" class="p-0"></label>
            <input asp-for="TransportationPrice" class="form-control" />
            <span asp-validation-for="TransportationPrice" class="text-danger"></span>
        </div>
        <div class="mb-3 row">
            <label asp-for="Tax" class="p-0"></label>
            <input asp-for="Tax" class="form-control" />
            <span asp-validation-for="Tax" class="text-danger"></span>
        </div>
        <div class="mb-3 row">
            <label asp-for="TotalPrice" class="p-0"></label>
            <input asp-for="TotalPrice" class="form-control" />
            <span asp-validation-for="TotalPrice" class="text-danger"></span>
        </div>

        <div class="row row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Create</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="SellForm" asp-action="GetSellForms" class="btn btn-outline-secondary border form-control">
                    Back To List
                </a>
            </div>
        </div>
    </div>
</form>

GolmohammadiProject/Views/SellForm/DeleteSellForm.cshtml
@using Golmohammadi.Models.Models.Factor
@model SellForm

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete</h2>
            <hr />
        </div>
        <div class="mb-3 row">
            <label asp-for="ProductName" class="p-0"></label>
            <input asp-for="ProductName" disabled class="form-control" />
        </div>
        <div class="mb-3 row">
            <label asp-for="Unit" class="p-0"></label>
            <input asp-for="Unit" disabled class="form-control" />
        </div>
        <div class="mb-3 row">
            <label asp-for="TransportationPrice" class="p-0"></label>
            <input asp-for="TransportationPrice" disabled class="form-control" />
        </div>
        <div class="mb-3 row">
            <label asp-for="Tax" class="p-0"></label>
            <input asp-for="Tax" disabled class="form-control" />
        </div>
        <div class="mb-3 row">
            <label asp-for="TotalPrice" class="p-0"></label>
            <input asp-for="TotalPrice" disabled class="form-control" />
        </div>

        <div class="row row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Delete</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="SellForm" asp-action="GetSellForms" class="btn btn-outline-secondary border form-control">
                    Back To List
                </a>
            </div>
        </div>
    </div>
</form>

GolmohammadiProject/Views/SellForm/EditSellForm.cshtml
@using Golmohammadi.Models.Models.Factor
@model SellForm

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit</h2>
            <hr />
        </div>
        <div class="mb-3 row">
            <label asp-for="ProductName" class="p-0"></label>
            <input asp-for="ProductName" class="form-control" />
            <span asp-validation-for="ProductName" class="text-danger"></span>
        </div>
        <div class="mb-3 row">
            <label asp-for="Unit" class="p-0"></label>
            <input asp-for="Unit" class="form-control" />
            <span asp-validation-for="Unit" class="text-danger"></span>
        </div>
        <div class="mb-3 row">
            <label asp-for="TransportationPrice" class="p-0"></label>
            <input asp-for="TransportationPrice" class="form-control" />
            <span asp-validation-for="TransportationPrice" class="text-danger"></span>
        </div>
        <div class="mb-3 row">
            <label asp-for="Tax" class="p-0"></label>
            <input asp-for="Tax" class="form-control" />
            <span asp-validation-for="Tax" class="text-danger"></span>
        </div>
        <div class="mb-3 row">
            <label asp-for="TotalPrice" class="p-0"></label>
            <input asp-for="TotalPrice" class="form-control" />
            <span asp-validation-for="TotalPrice" class="text-danger"></span>
        </div>

        <div class="row row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Update</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="SellForm" asp-action="GetSellForms" class="btn btn-outline-secondary border form-control">
                    Back To List
                </a>
            </div>
        </div>
    </div>
</form>

GolmohammadiProject/Views/SellForm/GetSellForms.cshtml
@using Golmohammadi.Models.Models.Factor
@model List<SellForm>

<div class="container">
    <div class="row pt-4 pb-2">
        <div class="col-6">
            <h2 class="text-primary">
                لیست فرم های فروش
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="SellForm" asp-action="CreateSellForm" class="btn btn-primary">
                <i class="bi bi-plus-square"></i> ایجاد فرم فروش
            </a>
        </div>
    </div>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>
                    نام محصول
                </th>
                <th>
                    واحد
                </th>
                <th>
                    هزینه حمل و نقل
                </th>
                <th>
                    مالیات
                </th>
                <th>
                    قیمت کل
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.ProductName</td>
                    <td>@item.Unit</td>
                    <td>@item.TransportationPrice</td>
                    <td>@item.Tax</td>
                    <td>@item.TotalPrice</td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="SellForm" asp-action="EditSellForm" asp-route-id="@item.Id" class="btn btn-primary">
                                <i class="bi bi-pencil-square"></i> Edit
                            </a>
                            <a asp-controller="SellForm" asp-action="DeleteSellForm" asp-route-id="@item.Id" class="btn btn-danger">
                                <i class="bi bi-trash3"></i> Delete
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>