GolmohammadiProject/Controllers/CustomerController.cs
using Golmohammadi.Models.Models.Customer;
using GolMohammadi.Business.CustomerServices;
using GolMohammadi.Business.ProductServices;
using Microsoft.AspNetCore.Mvc;

namespace GolmohammadiProject.Controllers
{
    public class CustomerController : Controller
    {
        private ICustomerService _customerService;

        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        [HttpGet]
        public async Task<IActionResult> GetCustomers()
        {
            List<Customers> customers = await _customerService.GetAllCustomers();
            return View(customers);
        }

        [HttpGet]
        public IActionResult CreateCustomer()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateCustomer(Customers customer)
        {
            await _customerService.Create(customer);
            return RedirectToAction("GetCustomers");
        }

        [HttpGet]
        public async Task<IActionResult> EditCustomer(int id)
        {
            var customer = await _customerService.GetById(id);
            return View(customer);
        }

        [HttpPost]
        public async Task<IActionResult> EditCustomer(Customers customer)
        {
            await _customerService.Update(customer);
            return RedirectToAction("GetCustomers");
        }

        [HttpGet]
        public async Task<IActionResult> DeleteCustomer(int id)
        {
            var customer = await _customerService.GetById(id);
            return View(customer);
        }

        [HttpPost, ActionName("DeleteCustomer")]
        public async Task<IActionResult> Delete(int id)
        {
            await _customerService.Delete(id);
            return RedirectToAction("GetCustomers");
        }
    }
}

GolmohammadiProject/Controllers/FactorController.cs
using Golmohammadi.ViewModels;
using GolMohammadi.Business.FactorService;
using Microsoft.AspNetCore.Mvc;

namespace GolmohammadiProject.Controllers
{
    public class FactorController : Controller
    {
        private IFactorService _factorService;

        public FactorController(IFactorService factorService)
        {
            _factorService = factorService;
        }

        [HttpGet]
        public async Task<IActionResult> Factor()
        {
            var AllItem = await _factorService.GetAllFactors();
            return View(AllItem);
        }

        [HttpGet]
        public async Task<IActionResult> GetCustomer(int id)
        {
            var customer = await _factorService.GetById(id);
            return View(customer);
        }

        [HttpGet]
        public async Task<IActionResult> GetProduct(int id)
        {
            var product = await _factorService.GetProduct(id);
            return View(product);
        }

        [HttpPost]
        public IActionResult Create(SellFactorViewModel sellFactorViewModel)
        {
            _factorService.Create(sellFactorViewModel);
            return Json("Factor Added");
        }
    }
}

GolmohammadiProject/Controllers/ProductController.cs
using Golmohammadi.Models.Models.Product;
using GolMohammadi.Business.ProductServices;
using Microsoft.AspNetCore.Mvc;

namespace GolmohammadiProject.Controllers;

public class ProductController : Controller
{
    private IProductService _productService;
    public ProductController(IProductService productService)
    {
        _productService = productService;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        List<Products> products = await _productService.GetAllProducts();
        return View(products);
    }

    [HttpGet]
    public IActionResult CreateProduct()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreateProduct(Products product)
    {
        await _productService.Create(product);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public async Task<IActionResult> EditProduct(int id)
    {
        var product = await _productService.GetById(id);
        return View(product);
    }

    [HttpPost]
    public async Task<IActionResult> EditProduct(Products product)
    {
        await _productService.Update(product);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public async Task<IActionResult> DeleteProduct(int id)
    {
        var product = await _productService.GetById(id);
        return View(product);
    }

    [HttpPost, ActionName("DeleteProduct")]
    public async Task<IActionResult> Delete(int id)
    {
        await _productService.Delete(id);
        return RedirectToAction("Index");
    }


    [HttpGet]
    public async Task<IActionResult> GetSubGroups()
    {
        List<SubGroup> subGroups = await _productService.GetAllSubGroup();
        return View(subGroups);
    }

    [HttpGet]
    public IActionResult CreateSubGroup()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreateSubGroup(SubGroup subGroup)
    {
        await _productService.CreateSubGroup(subGroup);
        return RedirectToAction("GetSubGroups");
    }

    [HttpGet]
    public async Task<IActionResult> EditSubGroup(int id)
    {
        var subGroup = await _productService.GetSubGroup(id);
        return View(subGroup);
    }

    [HttpPost]
    public async Task<IActionResult> EditSubGroup(SubGroup subGroup)
    {
        await _productService.UpdateSubGroup(subGroup);
        return RedirectToAction("GetSubGroups");
    }

    [HttpGet]
    public async Task<IActionResult> DeleteSubGroup(int id)
    {
        var subGroup = await _productService.GetSubGroup(id);
        return View(subGroup);
    }

    [HttpPost, ActionName("DeleteSubGroup")]
    public async Task<IActionResult> DeleteSubGroups(int id)
    {
        await _productService.DeleteSubGroup(id);
        return RedirectToAction("GetSubGroups");
    }



    [HttpGet]
    public async Task<IActionResult> GetProductGroups()
    {
        List<ProductGroup> productGroups = await _productService.GetAllProductGroup();
        return View(productGroups);
    }

    [HttpGet]
    public IActionResult CreateProductGroup()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreateProductGroup(ProductGroup productGroup)
    {
        await _productService.CreateProductGroup(productGroup);
        return RedirectToAction("GetProductGroups");
    }

    [HttpGet]
    public async Task<IActionResult> EditProductGroup(int id)
    {
        var productGroup = await _productService.GetProductGroup(id);
        return View(productGroup);
    }

    [HttpPost]
    public async Task<IActionResult> EditProductGroup(ProductGroup productGroup)
    {
        await _productService.UpdateProductGroup(productGroup);
        return RedirectToAction("GetProductGroups");
    }

    [HttpGet]
    public async Task<IActionResult> DeleteProductGroup(int id)
    {
        var productGroup = await _productService.GetProductGroup(id);
        return View(productGroup);
    }

    [HttpPost, ActionName("DeleteProductGroup")]
    public async Task<IActionResult> DeleteProductGroups(int id)
    {
        await _productService.DeleteProductGroup(id);
        return RedirectToAction("GetProductGroups");
    }
}

GolmohammadiProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GolmohammadiProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GolmohammadiProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">شرکت گل محمدی</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="GetCustomers">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Factor" asp-action="Factor">Factor</a>
                        </li>
                        <li class="dropdown">
                            <a class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                Products Categories
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <li>
                                    <a class="dropdown-item" asp-controller="Product" asp-action="GetProductGroups">Product Groups</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="Product" asp-action="GetSubGroups">Sub Groups</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="Product" asp-action="Index">Products</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 1403 - شرکت گل محمدی - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>